// Sprekerslijsten voor het tabblad SportsSpeakers / SportSpreker.
// AUTOMATISCH GEGENEREERD — niet met de hand bijwerken.
// Opnieuw maken: python "Commerciele dugout SPSP/genereer-sprekers.py"
// Bronnen: sprekers_{clinic,dagvoorzitter,lezing}_def_budgetrange.txt en sportspreker_kennisbank.md
// n = naam · s = sport · b = budgetrange · c = categorie
window.SPREKERS = {
"SportsSpeakers (NL)": [
  {n:"Alex Pastoor",s:"Voetbal",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Allard Lindhout",s:"Voetbal",b:"€ 1.500–2.000",c:"Lezing"},
  {n:"Anje-Marijcke van Boxtel",s:"Zeilen & surfen",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Annemiek van Vleuten",s:"Wielrennen",b:"€ 5.000–5.500",c:"Lezing"},
  {n:"Arno Bremer",b:"€ 1.500–2.000",c:"Dagvoorzitter"},
  {n:"Arnold Vanderlyde",s:"Boksen",b:"€ 2.500–3.000",c:"Clinic · Lezing"},
  {n:"Arvin Slagter",s:"Basketbal",b:"€ 2.500–3.000",c:"Clinic · Lezing"},
  {n:"Barbara Barend",b:"€ 4.000–4.500",c:"Dagvoorzitter"},
  {n:"Barbara de Loor",s:"Schaatsen",b:"€ 1.500–2.000",c:"Clinic · Dagvoorzitter · Lezing"},
  {n:"Barend van Deelen",b:"€ 1.000–1.500",c:"Dagvoorzitter"},
  {n:"Barry Schep",s:"Korfbal",b:"€ 500–1.000",c:"Clinic"},
  {n:"Bart Nolles",b:"€ 1.500–2.000",c:"Dagvoorzitter"},
  {n:"Bas Nijhuis",s:"Voetbal",b:"€ 4.500–5.000",c:"Lezing"},
  {n:"Bas van de Goor",s:"Volleybal",b:"€ 2.500–3.000",c:"Clinic"},
  {n:"Ben van der Burg",s:"Schaatsen",b:"€ 4.000–4.500",c:"Lezing"},
  {n:"Bjorn Kuipers",s:"Voetbal",b:"€ 6.500–7.000",c:"Lezing"},
  {n:"Björn van der Doelen",s:"Voetbal",b:"€ 1.500–2.000",c:"Lezing"},
  {n:"Bram Tankink",s:"Wielrennen",b:"€ 2.500–3.000",c:"Clinic · Lezing"},
  {n:"Brian Farley",s:"Honkbal",b:"€ 3.000–3.500",c:"Lezing"},
  {n:"Cedric Dumont",s:"Overige sporten",b:"€ 5.500–6.000",c:"Lezing"},
  {n:"Chris Woerts",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Danny Makkelie",s:"Voetbal",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Dennis van der Geest",s:"Judo",b:"€ 4.500–5.000",c:"Dagvoorzitter"},
  {n:"Diana Kuip",b:"€ 2.500–3.000",c:"Dagvoorzitter"},
  {n:"Dimeo van der Horst",s:"Basketbal",b:"€ 1.500–2.000",c:"Clinic"},
  {n:"Elsemieke Havenga",s:"Hockey",b:"€ 4.000–4.500",c:"Dagvoorzitter"},
  {n:"Epke Zonderland",s:"Turnen",b:"€ 6.500–7.000",c:"Lezing"},
  {n:"Erben Wennemars",s:"HYROX · Schaatsen",b:"€ 2.000–4.000",c:"Clinic · Dagvoorzitter · Lezing"},
  {n:"Erik Hulzebosch",s:"Schaatsen",b:"€ 2.500–3.000",c:"Lezing"},
  {n:"Esther Vergeer",s:"Tennis",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Eythora Thorsdottir",s:"Turnen",b:"€ 1.500–2.000",c:"Clinic"},
  {n:"Ferry Weertman",s:"Zwemmen",b:"€ 2.000–2.500",c:"Clinic"},
  {n:"Foppe de Haan",s:"Voetbal",b:"€ 4.000–4.500",c:"Lezing"},
  {n:"Gerard Kemkers",s:"Schaatsen",b:"€ 3.000–3.500",c:"Lezing"},
  {n:"Gerd-Jan Poortman",s:"Zeilen & surfen",b:"€ 2.500–3.000",c:"Lezing"},
  {n:"Gert Jakobs",s:"Wielrennen",b:"€ 1.500–2.000",c:"Clinic · Lezing"},
  {n:"Giedo van der Garde",s:"Autosport",b:"€ 4.500–5.000",c:"Dagvoorzitter · Lezing"},
  {n:"Gregory Sedoc",s:"Atletiek",b:"€ 3.500–4.000",c:"Clinic · Dagvoorzitter · Lezing"},
  {n:"Guus Hiddink",s:"Voetbal",b:"€ 7.500–8.000",c:"Lezing"},
  {n:"Hans van Breukelen",s:"Voetbal",b:"€ 2.500–3.000",c:"Lezing"},
  {n:"Hein Noortman",s:"Bergbeklimmen",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Helene Hendriks",b:"€ 7.500–8.000",c:"Dagvoorzitter"},
  {n:"Henk Grol",s:"Judo",b:"€ 2.500–3.000",c:"Clinic"},
  {n:"Hidde Weersma",s:"HYROX",b:"€ 500–1.000",c:"Clinic"},
  {n:"Humberto Tan",b:"€ 11.000–11.500",c:"Dagvoorzitter"},
  {n:"Ireen Wüst",s:"Schaatsen",b:"€ 6.000–6.500",c:"Lezing"},
  {n:"Irene Schouten",s:"Schaatsen",b:"€ 5.500–6.000",c:"Lezing"},
  {n:"Jacco Verhaeren",s:"Zwemmen",b:"€ 6.000–6.500",c:"Lezing"},
  {n:"Jack Plooij",s:"Autosport",b:"€ 3.000–3.500",c:"Lezing"},
  {n:"Jan Lammers",s:"Autosport",b:"€ 3.000–3.500",c:"Lezing"},
  {n:"Jan Smeekens",s:"Schaatsen",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Jan van Halst",s:"Voetbal",b:"€ 3.000–3.500",c:"Clinic · Lezing"},
  {n:"Jeffrey Hoogland",s:"Wielrennen",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Jeroen Otter",s:"Shorttrack",b:"€ 3.000–3.500",c:"Lezing"},
  {n:"Jeroen Stomphorst",b:"€ 3.500–4.000",c:"Dagvoorzitter"},
  {n:"Jesper Jobse",s:"Basketbal",b:"€ 1.000–1.500",c:"Clinic"},
  {n:"Jochem Uytdehaage",s:"Schaatsen",b:"€ 2.500–3.000",c:"Lezing"},
  {n:"John de Wolf",s:"Voetbal",b:"€ 2.500–3.000",c:"Lezing"},
  {n:"John van Zweden",s:"Voetbal",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Joop Alberda",s:"Volleybal",b:"€ 2.500–3.000",c:"Lezing"},
  {n:"Joyce Sombroek",s:"Hockey",b:"€ 2.500–3.000",c:"Lezing"},
  {n:"Kim Lammers",s:"Hockey",b:"€ 2.500–3.000",c:"Lezing"},
  {n:"Leontien van Moorsel",s:"Wielrennen",b:"€ 3.500–4.000",c:"Clinic · Lezing"},
  {n:"Maaike Head",s:"Roeien",b:"€ 1.500–2.000",c:"Lezing"},
  {n:"Maarten van der Weijden",s:"Zwemmen",b:"€ 4.500–5.000",c:"Lezing"},
  {n:"Marc Lammers",s:"Hockey",b:"€ 5.000–5.500",c:"Lezing"},
  {n:"Marc van de Kuilen",s:"Basketbal",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Marianne Timmer",s:"Schaatsen",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Marijn de Vries",s:"Wielrennen",b:"€ 2.000–2.500",c:"Dagvoorzitter · Lezing"},
  {n:"Marit Bouwmeester",s:"Zeilen & surfen",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Mark Tuitert",s:"Schaatsen",b:"€ 4.500–5.000",c:"Lezing"},
  {n:"Marloes Wesselink",s:"Volleybal",b:"€ 1.500–2.000",c:"Dagvoorzitter"},
  {n:"Martin Hersman",s:"Schaatsen",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Mary Kok-Willemsen",s:"Voetbal",b:"€ 3.000–3.500",c:"Lezing"},
  {n:"Merijn Zeeman",s:"Wielrennen",b:"€ 7.500–8.000",c:"Lezing"},
  {n:"Michael Boogerd",s:"Wielrennen",b:"€ 3.000–3.500",c:"Clinic · Lezing"},
  {n:"Nicolien Sauerbreij",s:"Snowboarden",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Nouchka Fontijn",s:"Boksen",b:"€ 2.500–3.000",c:"Clinic · Lezing"},
  {n:"Olga Commandeur",b:"€ 1.000–1.500",c:"Lezing"},
  {n:"Paul Haarhuis",s:"Tennis",b:"€ 1.500–2.000",c:"Clinic"},
  {n:"Peter Heerschop",b:"€ 3.000–3.500",c:"Dagvoorzitter · Lezing"},
  {n:"Pieter van den Hoogenband",s:"Zwemmen",b:"€ 7.500–8.000",c:"Lezing"},
  {n:"Ranomi Kromowidjojo",s:"Zwemmen",b:"€ 4.500–5.000",c:"Clinic · Lezing"},
  {n:"Remy Bonjasky",s:"Boksen",b:"€ 2.500–3.000",c:"Clinic · Dagvoorzitter · Lezing"},
  {n:"Renate Wennemars",b:"€ 1.000–1.500",c:"Dagvoorzitter"},
  {n:"Richard Plugge",s:"Wielrennen",b:"€ 4.500–5.000",c:"Lezing"},
  {n:"Richard van Hooijdonk",b:"€ 4.500–5.000",c:"Lezing"},
  {n:"Rob Kamphues",s:"Autosport",b:"€ 4.000–4.500",c:"Lezing"},
  {n:"Robert Doornbos",s:"Autosport",b:"€ 7.500–8.000",c:"Lezing"},
  {n:"Robert Eenhoorn",s:"Honkbal",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Robert Meeuwsen",s:"Volleybal",b:"€ 2.500–3.000",c:"Clinic"},
  {n:"Robin van Galen",s:"Waterpolo",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Rocky Hehakaija",s:"Voetbal",b:"€ 5.000–5.500",c:"Dagvoorzitter"},
  {n:"Rolf Schrama",s:"Zeilen & surfen",b:"€ 2.500–3.000",c:"Lezing"},
  {n:"Samantha van Wijk",b:"€ 2.500–3.000",c:"Dagvoorzitter"},
  {n:"Sander Kleikers",b:"€ 2.500–3.000",c:"Dagvoorzitter"},
  {n:"Serdar Gözübüyük",s:"Voetbal",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Sherida Spitse",s:"Voetbal",b:"€ 2.500–3.000",c:"Clinic"},
  {n:"Shona Shukrula",s:"Voetbal",b:"€ 3.000–3.500",c:"Lezing"},
  {n:"Sjoerd Marijne",s:"Hockey",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Soufiane Touzani",s:"Voetbal",b:"€ 7.500–8.000",c:"Lezing"},
  {n:"Suse van Kleef",b:"€ 5.000–5.500",c:"Dagvoorzitter"},
  {n:"Suzanne Huurman",b:"€ 4.500–5.000",c:"Dagvoorzitter"},
  {n:"Tess Wester",s:"Handbal",b:"€ 2.500–3.000",c:"Clinic"},
  {n:"Tessa Veldhuis",s:"Rugby",b:"€ 1.500–2.000",c:"Dagvoorzitter"},
  {n:"Thomas Dekker",s:"Wielrennen",b:"€ 3.500–4.000",c:"Clinic"},
  {n:"Tim Coronel",s:"Autosport",b:"€ 2.000–2.500",c:"Lezing"},
  {n:"Toine van Peperstraten",b:"€ 4.000–4.500",c:"Dagvoorzitter"},
  {n:"Tom Coronel",s:"Autosport",b:"€ 3.000–3.500",c:"Lezing"},
  {n:"Tom Dumoulin",s:"Wielrennen",b:"€ 7.500–8.000",c:"Lezing"},
  {n:"Toon Gerbrands",s:"Volleybal",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Twan Huys",b:"€ 9.000–9.500",c:"Dagvoorzitter"},
  {n:"Wilco van Rooijen",s:"Bergbeklimmen",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Wilfred Genee",b:"€ 7.500–8.000",c:"Dagvoorzitter"},
  {n:"Willem van Hanegem",s:"Voetbal",b:"€ 4.500–5.000",c:"Lezing"},
  {n:"Wim Kieft",s:"Voetbal",b:"€ 3.500–4.000",c:"Lezing"},
  {n:"Wouter de Jong",b:"€ 3.000–3.500",c:"Lezing"}
],
"SportSpreker (BE)": [
  {n:"Aad de Mos",s:"Voetbal"},
  {n:"Aagje Vanwalleghem",s:"Turnen",b:"€ 2.200"},
  {n:"Adrie van der Poel",s:"Veldrijden",b:"€ 1.250"},
  {n:"Ageeth Boomgaardt",s:"Hockey"},
  {n:"Akwasi Frimpong",s:"Bobslee",b:"€ 1.800"},
  {n:"An Soenens",s:"Badminton"},
  {n:"Ann Wauters",s:"Basketbal",b:"€ 3.500"},
  {n:"Anouk Doore",s:"Bergbeklimmen"},
  {n:"Anthony Kumpen",s:"Autosport",b:"€ 2.400"},
  {n:"Arnold Vanderlyde",s:"Boksen",b:"€ 2.500"},
  {n:"Arthur Van Doren",s:"Hockey",b:"€ 2.500"},
  {n:"Aster Nzeyimana",s:"Voetbal",b:"€ 3.000"},
  {n:"Barbara Torfs",b:"€ 1.000"},
  {n:"Bart Swings",s:"Schaatsen"},
  {n:"Bart Veldkamp",s:"Schaatsen"},
  {n:"Bart Wellens",s:"Veldrijden",b:"€ 1.500"},
  {n:"Bert De Backer",s:"Wielrennen",b:"€ 2.000"},
  {n:"Björn Kuipers",s:"Voetbal",b:"€ 6.500"},
  {n:"Bram Tankink",s:"Wielrennen",b:"€ 2.500"},
  {n:"Bram Van Driessche",s:"Voetbal",b:"€ 1.300"},
  {n:"Carine Verbauwen",s:"Zwemmen",b:"€ 750"},
  {n:"Carl Huybrechts",s:"Voetbal",b:"€ 1.500"},
  {n:"Carl Maes",s:"Tennis",b:"€ 1.500"},
  {n:"Carolien Van Den Bosch",b:"€ 2.000"},
  {n:"Cedric Dumont",b:"€ 5.000"},
  {n:"Charlotte De Vos",s:"Hockey",b:"€ 1.200"},
  {n:"David Steegen",s:"Voetbal"},
  {n:"Dieter Van der Eyken",s:"windsurfen",b:"€ 1.200"},
  {n:"Dominic Rossi",s:"/",b:"€ 1.500"},
  {n:"Dominique Baeyens",s:"volleybal",b:"€ 1.250"},
  {n:"Dominique Monami",s:"tennis",b:"€ 2.400"},
  {n:"Dries Koekelkoren",s:"beachvolley",b:"€ 1.000"},
  {n:"Eddy Casteels",s:"Basketbal",b:"€ 1.500"},
  {n:"Eddy Demarez",s:"journalist",b:"€ 1.500"},
  {n:"Eddy Planckaert",s:"wielrenner",b:"€ 2.400"},
  {n:"Elfje Willemsen",s:"speerwerpen, bobslee",b:"€ 750"},
  {n:"Elien Allaert",s:"Paralympisch"},
  {n:"Eline Berings",s:"hordelopen",b:"€ 750"},
  {n:"Elke Weylandt",s:"Wielrennen",b:"€ 1.400"},
  {n:"Ellen Schouppe",b:"€ 2.850"},
  {n:"Emmanuel Stockbroeckx",s:"hockey",b:"€ 1.000"},
  {n:"Emmanuel Vanluchene",s:"Zwemmen",b:"€ 1.000"},
  {n:"Eric Gerets",s:"Voetbal",b:"€ 2.500"},
  {n:"Erwin Van den Sande",s:"Voetbal",b:"€ 1.000"},
  {n:"Evi Van Acker",s:"zeilen",b:"€ 2.250"},
  {n:"Evy Gruyaert",b:"€ 2.500"},
  {n:"Félix Denayer",s:"Hockey",b:"€ 3.800"},
  {n:"Floris Wouterson"},
  {n:"Frank De Bleeckere",s:"Voetbal",b:"€ 2.000"},
  {n:"Frank Raes",s:"Voetbal",b:"€ 1.500"},
  {n:"Franky Van der Elst",s:"Voetbal",b:"€ 2.000"},
  {n:"Frederik Vandormael",s:"schermen",b:"€ 750"},
  {n:"Geert De Mulder"},
  {n:"Gella Vandecaveye",s:"judo",b:"€ 1.875"},
  {n:"Gunnar De Lepeleire",s:"Basketbal"},
  {n:"Hanna Mariën",s:"Bobslee"},
  {n:"Hanne Maudens",s:"Atletiek"},
  {n:"Hannelore Vens",s:"Zwemmen",b:"€ 1.000"},
  {n:"Hans Bouscholte",s:"Zeiler",b:"€ 1.500"},
  {n:"Hans van Alphen",s:"Atletiek",b:"€ 2.000"},
  {n:"Hans van Breukelen",s:"Voetbal"},
  {n:"Henk Kraaijenhof",s:"Atletiek",b:"€ 2.000"},
  {n:"Ilse Heylen",s:"Judo",b:"€ 1.250"},
  {n:"Imke Courtois"},
  {n:"Inez Swinnen",s:"Zwemmen",b:"€ 1.400"},
  {n:"Jacques Borlée",s:"Atletiek",b:"€ 5.000"},
  {n:"Jan Ceulemans",s:"Voetbal",b:"€ 2.000"},
  {n:"Jan De Schepper",s:"Roeien",b:"€ 1.500"},
  {n:"Jan Evenepoel",b:"€ 1.300"},
  {n:"Jan Olbrecht",s:"Zwemmen",b:"€ 1.500"},
  {n:"Jean-Marie Pfaff",s:"Voetbal",b:"€ 2.500"},
  {n:"Jean-Michel Saive",s:"Tafeltennis",b:"€ 2.000"},
  {n:"Jef Brouwers"},
  {n:"Jef Geys",b:"€ 1.250"},
  {n:"Jelle Wallays",s:"Wielrennen",b:"€ 1.500"},
  {n:"Jeroen Keymolen",s:"Atletiek",b:"€ 1.350"},
  {n:"Jeroen Nollet",b:"€ 1.250"},
  {n:"Johan Boskamp",s:"Voetbal",b:"€ 3.000"},
  {n:"Johan De Keyser",b:"€ 1.800"},
  {n:"Johan Museeuw",s:"Wielrennen",b:"€ 1.500"},
  {n:"Johan Van Herck",s:"Tennis",b:"€ 1.250"},
  {n:"John Heymans",s:"Hockey",b:"€ 3.000"},
  {n:"Jordy Mottart"},
  {n:"Kim Gevaert",s:"Atletiek en bobslee"},
  {n:"Kimberly Buys",s:"Zwemmen"},
  {n:"Koen Gonnissen",s:"Roeien",b:"€ 4.250"},
  {n:"Koen Weijland"},
  {n:"Lieven Van Gils",b:"€ 1.500"},
  {n:"Lieven Van Linden",s:"Roeien",b:"€ 2.000"},
  {n:"Lisa Van den Bunder"},
  {n:"Louise Carton",s:"Atletiek"},
  {n:"Luc Apers",s:"Veldrijden",b:"€ 800"},
  {n:"Luc Nilis",s:"Voetbal",b:"€ 1.500"},
  {n:"Luc Rademakers",b:"€ 1.000"},
  {n:"Luca Brecel",b:"€ 1.200"},
  {n:"Maarten Breckx",s:"Voetbal",b:"€ 2.000"},
  {n:"Maarten Vangramberen",s:"Voetbal",b:"€ 2.000"},
  {n:"Manon Claeys",s:"Paralympisch",b:"€ 1.500"},
  {n:"Marc Herremans",s:"Triatlon",b:"€ 2.750"},
  {n:"Marc Lammers",s:"Hockey",b:"€ 6.000"},
  {n:"Mathieu van der Poel",s:"Veldrijden",b:"€ 4.000"},
  {n:"Matthias Haspeslagh"},
  {n:"Max Icardi",b:"€ 1.400"},
  {n:"Maxim Wouters",s:"Voetbal",b:"€ 1.200"},
  {n:"Michaël Bultheel",b:"€ 1.500"},
  {n:"Michaël Verschaeve",s:"Atletiek",b:"€ 900"},
  {n:"Michèle George",s:"Paralympisch",b:"€ 3.000"},
  {n:"Nicky Degrendele",s:"Wielrennen",b:"€ 1.000"},
  {n:"Olivier Verhaege",b:"€ 1.400"},
  {n:"Pascal Kina",s:"Hockey"},
  {n:"Paul Van Den Bosch",s:"Atletiek",b:"€ 2.700"},
  {n:"Peter Genyn",s:"Atletiek",b:"€ 1.500"},
  {n:"Pieter Maes"},
  {n:"Pieter Timmers",s:"Zwemmen",b:"€ 1.500"},
  {n:"Richard Van Hooijdonk",b:"€ 5.990"},
  {n:"Rik Vanwalleghem",s:"Wielrennen"},
  {n:"Rob Wuijster",s:"Hockey"},
  {n:"Roger De Vlaeminck",s:"Veldrijden",b:"€ 1.000"},
  {n:"Ronald Gaastra",s:"Zwemmen",b:"€ 1.000"},
  {n:"Ruben Neyens",s:"Tennis",b:"€ 600"},
  {n:"Saartje Vandendriessche",b:"€ 1.500"},
  {n:"Sabine Appelmans",s:"Tennis",b:"€ 1.500"},
  {n:"Sandra Bekkari",b:"€ 2.000"},
  {n:"Saskia de Coster"},
  {n:"Saskia de Costers",b:"€ 1.500"},
  {n:"Sebastien Bellin",s:"Basketbal",b:"€ 3.500"},
  {n:"Sef Vergoossen",s:"Voetbal",b:"€ 1.500"},
  {n:"Sep Vanmarcke",s:"Wielrennen",b:"€ 2.000"},
  {n:"Seppe Smits",s:"Snowboarden",b:"€ 1.500"},
  {n:"Serge Crevecoeur",s:"Basketbal",b:"€ 1.000"},
  {n:"Serge Haubourdin"},
  {n:"Servaas Bingé",s:"Wielrennen",b:"€ 2.000"},
  {n:"Simon Dewulf",b:"€ 1.000"},
  {n:"Sofie Lenaerts",s:"Roeien",b:"€ 2.000"},
  {n:"Stefaan Maene",s:"Zwemmen",b:"€ 1.000"},
  {n:"Stefan Everts",b:"€ 1.200"},
  {n:"Steve Janssen",b:"€ 1.000"},
  {n:"Steven Smet",s:"Voetbal"},
  {n:"Suyin Aerts",b:"€ 2.500"},
  {n:"Sven Nys",s:"Wielrennen",b:"€ 3.500"},
  {n:"Sven Vanthourenhout",s:"Wielrennen",b:"€ 2.000"},
  {n:"Tessa Wullaert",s:"Voetbal",b:"€ 1.250"},
  {n:"Tia Hellebaut",s:"Atletiek",b:"€ 2.000"},
  {n:"Tim De Vilder",b:"€ 1.350"},
  {n:"Tom Coninx"},
  {n:"Tom Franssens"},
  {n:"Viktor Van der Veken",s:"Atletiek",b:"€ 900"},
  {n:"Vincent Vanasch",s:"Hockey",b:"€ 3.000"},
  {n:"Ward Lemmelijn",s:"Roeien",b:"€ 2.000"},
  {n:"Wesley Sonck",s:"Voetbal",b:"€ 2.500"},
  {n:"Wilco van Rooijen",s:"Bergbeklimmen"},
  {n:"Wim Smets",s:"Bergbeklimmen",b:"€ 2.500"},
  {n:"Yanina Wickmayer Extennister",s:"Tennis",b:"€ 1.500"},
  {n:"Yannick Ferrera",s:"Voetbal",b:"€ 2.000"},
  {n:"Yves Verbeeck",b:"€ 1.000"},
  {n:"Zeb Jacobs",s:"Roeien",b:"€ 1.000"}
]
};
