-- ============================================================
--  DE COMMERCIËLE DUGOUT · Supabase schema
--  Plak dit volledig in: Supabase → SQL Editor → New query → Run
--  Regio: EU (Frankfurt) i.v.m. AVG (er staat persoonsdata van contacten in).
-- ============================================================

-- 1) Hoofdtabel: alle saleskansen (de "kaarten") -------------
create table if not exists public.deals (
  id              bigint generated by default as identity primary key,
  klant           text    not null default '',
  contact         text    not null default '',
  functie         text    not null default '',
  email           text    not null default '',
  tel             text    not null default '',
  owner           text    not null default '',
  unit            text    not null default '',
  merk            text    not null default '',
  waarde          integer not null default 0,
  fase            text    not null default '1e salescontact',
  type            text    not null default 'Fysiek',
  actie           text    not null default 'Saleskans',
  laatste         date,
  bijgewerkt      date,
  opm             text    not null default '',
  bijlagen        jsonb   not null default '[]'::jsonb,

  -- archief / status -----------------------------------------
  -- 'actief'  = staat in de pipeline
  -- 'benut'   = succesvol afgerond  -> Benutte saleskansen
  -- 'onbenut' = afgevallen/verwijderd -> Onbenutte saleskansen
  status          text    not null default 'actief',

  won_at          timestamptz,   -- moment dat 'ie in de laatste fase kwam (winst)
  archived_at     timestamptz,   -- moment dat 'ie echt naar het archief ging
  afsluit_notitie text,          -- "Hoe is deze kans benut?" (verplicht bij winst)
  verwijder_reden text,          -- "Waarom is dit niet afgesloten?" (verplicht bij verwijderen)

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Handige indexen voor de views
create index if not exists deals_status_idx on public.deals (status);
create index if not exists deals_won_at_idx on public.deals (won_at);

-- updated_at automatisch bijwerken bij elke wijziging
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists deals_set_updated_at on public.deals;
create trigger deals_set_updated_at
  before update on public.deals
  for each row execute function public.set_updated_at();

-- ============================================================
-- 2) Row Level Security
--    LET OP: login/beveiliging is (voorlopig) geparkeerd.
--    Onderstaande policy geeft IEDEREEN met de anon-key lees/schrijf-
--    toegang. Prima voor de testfase, maar dit MOET dichtgezet worden
--    zodra we auth toevoegen — er staat persoonsdata in (AVG).
-- ============================================================
alter table public.deals enable row level security;

drop policy if exists "dugout_anon_full_access" on public.deals;
create policy "dugout_anon_full_access"
  on public.deals
  for all
  to anon
  using (true)
  with check (true);

-- ============================================================
-- 3) OPTIONEEL — 13 testkaarten om meteen data te zien.
--    Laat dit blok weg als je leeg wilt starten.
-- ============================================================
insert into public.deals
  (klant, contact, functie, email, tel, owner, unit, merk, waarde, fase, type, actie, laatste, bijgewerkt, opm, status)
values
 -- Univé Het Groene Hart (2 kansen)
 ('Univé Het Groene Hart','Sandra Bosch','Coördinator Sponsoring','s.bosch@unive.nl','+31 6 42 11 78 90','Geoffrey','HOS Algemeen','Feyenoord',40000,'Propositie/voorstel gedeeld','Online meeting','Saleskans','2026-07-05','2026-07-05','Voorstel gedeeld voor regionale zichtbaarheid rond Feyenoord. Wacht op interne akkoord.','actief'),
 ('Univé Het Groene Hart','Sandra Bosch','Coördinator Sponsoring','s.bosch@unive.nl','+31 6 42 11 78 90','Dille','SPEX','Premier Padel',18000,'Oriënterend gesprek','Telefonisch','Terugbellen','2026-06-24','2026-06-24','Interesse in padel-activatie via Premier Padel. Budget na de zomer duidelijk.','actief'),
 -- Univé Centraal
 ('Univé Centraal','Mark Visser','Manager Merkactivatie','mark.visser@unive.nl','+31 6 18 22 90 55','Michelle','HOS Algemeen','Supporter van Sport',55000,'Voorstel akkoord','Fysiek','Ongoing','2026-07-08','2026-07-08','Akkoord op hoofdlijnen voor het ''Supporter van Sport''-programma. Contract in de maak.','actief'),
 -- ARAG (2 kansen)
 ('ARAG','Sanne de Groot','Hoofd Sponsoring','s.degroot@arag.nl','+31 6 21 44 88 03','Bart','HYROX','HYROX',70000,'Propositie/voorstel gedeeld','Online meeting','Saleskans','2026-07-09','2026-07-09','Interesse als titelsponsor van een HYROX-event. Voorstel gedeeld, wacht op reactie.','actief'),
 ('ARAG','Ruben Smit','Inkoop & Partnerships','r.smit@arag.nl','+31 6 21 55 90 12','Koen','HOS Algemeen','KNVB',90000,'Oriënterend gesprek','Fysiek','Ongoing','2026-06-30','2026-06-30','Verkennend gesprek over een KNVB-koppeling. Enthousiast; vervolg inplannen.','actief'),
 -- Univé Dichtbij
 ('Univé Dichtbij','Marijke de Wit','Regiomanager Sponsoring','m.dewit@unive.nl','+31 6 18 55 33 21','Tom T','HOS Algemeen','sc Heerenveen',35000,'1e salescontact','E-mail','Saleskans','2026-07-07','2026-07-07','Introductie gestuurd voor een samenwerking rond sc Heerenveen.','actief'),
 -- Upfront
 ('Upfront','Noor El Amrani','Partnerships Manager','noor@upfront.nl','+31 6 51 88 22 47','Michelle','BAT','BAT · Strategie',25000,'Oriënterend gesprek','Online meeting','Ongoing','2026-07-03','2026-07-03','Meedenken over de BAT-strategie en inzet van creators.','actief'),
 -- Eurojackpot · afgerond in archief (5)
 ('Eurojackpot','Daniël Bakker','Media & Partnerships','d.bakker@eurojackpot.eu','+31 6 33 47 82 10','Bart','HOS Algemeen','PSV',120000,'Contractueel/formeel vastgelegd','Fysiek','Ongoing','2026-06-10','2026-06-19','Meerjarige clubdeal met PSV rond; getekend en geactiveerd.','benut'),
 ('Eurojackpot','Daniël Bakker','Media & Partnerships','d.bakker@eurojackpot.eu','+31 6 33 47 82 10','Koen','HOS Algemeen','AZ',85000,'Contractueel/formeel vastgelegd','Online meeting','Ongoing','2026-06-05','2026-06-15','AZ-partnership getekend voor het komende seizoen.','benut'),
 ('Eurojackpot','Daniël Bakker','Media & Partnerships','d.bakker@eurojackpot.eu','+31 6 33 47 82 10','Geoffrey','HOS Algemeen','FC Twente',60000,'Contractueel/formeel vastgelegd','Fysiek','Ongoing','2026-05-28','2026-06-06','FC Twente-deal afgerond, activatie loopt.','benut'),
 ('Eurojackpot','Daniël Bakker','Media & Partnerships','d.bakker@eurojackpot.eu','+31 6 33 47 82 10','Dille','HOS Algemeen','Roda JC',30000,'Contractueel/formeel vastgelegd','Telefonisch','Ongoing','2026-06-18','2026-06-27','Roda JC contractueel vastgelegd.','benut'),
 ('Eurojackpot','Daniël Bakker','Media & Partnerships','d.bakker@eurojackpot.eu','+31 6 33 47 82 10','Michelle','HOS Algemeen','NEC',40000,'Contractueel/formeel vastgelegd','Online meeting','Ongoing','2026-06-22','2026-07-01','NEC-samenwerking rond en getekend.','benut'),
 -- Eurojackpot · nog open (3)
 ('Eurojackpot','Daniël Bakker','Media & Partnerships','d.bakker@eurojackpot.eu','+31 6 33 47 82 10','Bart','HOS Algemeen','De Graafschap',28000,'Propositie/voorstel gedeeld','Telefonisch','Saleskans','2026-07-04','2026-07-04','Voorstel gedeeld voor De Graafschap. Wacht op akkoord.','actief'),
 ('Eurojackpot','Daniël Bakker','Media & Partnerships','d.bakker@eurojackpot.eu','+31 6 33 47 82 10','Koen','HOS Algemeen','Heracles',32000,'Oriënterend gesprek','E-mail','Terugbellen','2026-06-26','2026-06-26','Eerste interesse van Heracles. Half juli opvolgen.','actief'),
 ('Eurojackpot','Daniël Bakker','Media & Partnerships','d.bakker@eurojackpot.eu','+31 6 33 47 82 10','Geoffrey','HOS Algemeen','Volendam',26000,'1e salescontact','E-mail','Saleskans','2026-07-06','2026-07-06','Introductie gestuurd voor een samenwerking met FC Volendam.','actief'),
 -- HYROX (3 kansen)
 ('HYROX','Mark de Vries','Brand Manager','m.devries@rexona.com','+31 6 22 41 88 09','Bart','HYROX','Rexona',65000,'Voorstel akkoord','Online meeting','Ongoing','2026-07-08','2026-07-08','Rexona akkoord op activatie bij de events. Contract opstellen.','actief'),
 ('HYROX','Jeroen Willems','Wervingscampagnes','partnerships@defensie.nl','+31 6 15 70 33 21','Koen','HYROX','Defensie',50000,'Oriënterend gesprek','Fysiek','Ongoing','2026-06-28','2026-06-28','Defensie geïnteresseerd in recruitment-activatie bij HYROX-events.','actief'),
 ('HYROX','Noor El Amrani','Partnerships Manager','noor@upfront.nl','+31 6 51 88 22 47','Michelle','HYROX','Upfront',20000,'Propositie/voorstel gedeeld','Online meeting','Saleskans','2026-07-02','2026-07-02','Upfront wil content en creators leveren rond HYROX.','actief'),
 -- Atleten (4 kansen)
 ('Atleten','Wouter Jansen','Athlete Management','w.jansen@houseofathletes.nl','+31 6 27 44 90 11','Dille','Athletes','Suzanne Schulting · Upfront',30000,'Propositie/voorstel gedeeld','Online meeting','Saleskans','2026-07-05','2026-07-05','Upfront als sponsor voor Suzanne Schulting; voorstel gedeeld.','actief'),
 ('Atleten','Wouter Jansen','Athlete Management','w.jansen@houseofathletes.nl','+31 6 27 44 90 11','Tom T','Athletes','Suzanne Schulting · Team Essent',45000,'Voorstel akkoord','Fysiek','Ongoing','2026-07-09','2026-07-09','Essent akkoord op teamsponsoring rond Schulting. Contract in de maak.','actief'),
 ('Atleten','Wouter Jansen','Athlete Management','w.jansen@houseofathletes.nl','+31 6 27 44 90 11','Dille','Athletes','Jenning de Boo · Upfront',22000,'Oriënterend gesprek','Telefonisch','Terugbellen','2026-06-27','2026-06-27','Upfront interesse in Jenning de Boo. Half juli terugbellen.','actief'),
 ('Atleten','Wouter Jansen','Athlete Management','w.jansen@houseofathletes.nl','+31 6 27 44 90 11','Geoffrey','Athletes','Botic van de Zandschulp · Indian Maharaja',38000,'1e salescontact','E-mail','Saleskans','2026-07-06','2026-07-06','Indian Maharaja (tennis) interesse in Botic van de Zandschulp. Intro gestuurd.','actief'),
 -- Onbenutte saleskansen (afgevallen)
 ('Eurojackpot','Daniël Bakker','Media & Partnerships','d.bakker@eurojackpot.eu','+31 6 33 47 82 10','Bart','HOS Algemeen','Fortuna Sittard',24000,'Propositie/voorstel gedeeld','Online meeting','Later contact opnemen','2026-06-12','2026-06-19','Voorstel gedeeld, maar de club koos voor een andere partner.','onbenut'),
 ('Univé Zuid-Nederland','Peter Hendriks','Manager Marketing','p.hendriks@unive.nl','+31 6 27 90 14 66','Geoffrey','Schaatsen','Schaatsclinics',20000,'Oriënterend gesprek','Telefonisch','Later contact opnemen','2026-05-30','2026-06-05','Interesse was er wel, maar het budget kwam dit seizoen niet rond.','onbenut'),
 -- Benutte saleskansen · andere klanten (bundeling-demo in archief)
 ('ARAG','Sanne de Groot','Hoofd Sponsoring','s.degroot@arag.nl','+31 6 21 44 88 03','Tom T','Schaatsen','Schaatsclinics 2025',28000,'Contractueel/formeel vastgelegd','Fysiek','Ongoing','2026-05-20','2026-05-27','Schaatsclinics-seizoen 2025 volledig uitverkocht en geactiveerd.','benut'),
 ('ARAG','Ruben Smit','Inkoop & Partnerships','r.smit@arag.nl','+31 6 21 55 90 12','Bart','HOS Algemeen','Dam tot Damloop',42000,'Contractueel/formeel vastgelegd','Online meeting','Ongoing','2026-06-08','2026-06-16','Titelpartner Dam tot Damloop rond; contract getekend.','benut'),
 ('Univé Dichtbij','Marijke de Wit','Regiomanager Sponsoring','m.dewit@unive.nl','+31 6 18 55 33 21','Geoffrey','HOS Algemeen','sc Cambuur',30000,'Contractueel/formeel vastgelegd','Fysiek','Ongoing','2026-06-14','2026-06-21','Regionale sc Cambuur-samenwerking getekend.','benut');

-- Zet de afsluit-details voor de 5 afgeronde Eurojackpot-kansen (Benutte saleskansen)
update public.deals set won_at='2026-06-12', archived_at='2026-06-19', afsluit_notitie='Meerjarige clubdeal met PSV rond; getekend en geactiveerd.' where klant='Eurojackpot' and merk='PSV';
update public.deals set won_at='2026-06-08', archived_at='2026-06-15', afsluit_notitie='AZ-partnership getekend voor het komende seizoen.' where klant='Eurojackpot' and merk='AZ';
update public.deals set won_at='2026-05-30', archived_at='2026-06-06', afsluit_notitie='FC Twente-deal afgerond, activatie loopt.' where klant='Eurojackpot' and merk='FC Twente';
update public.deals set won_at='2026-06-20', archived_at='2026-06-27', afsluit_notitie='Roda JC contractueel vastgelegd.' where klant='Eurojackpot' and merk='Roda JC';
update public.deals set won_at='2026-06-24', archived_at='2026-07-01', afsluit_notitie='NEC-samenwerking rond en getekend.' where klant='Eurojackpot' and merk='NEC';

-- Archiveer-details voor de nieuwe benutte kansen van andere klanten
update public.deals set won_at='2026-05-22', archived_at='2026-05-27', afsluit_notitie='Schaatsclinics-seizoen 2025 volledig uitverkocht en geactiveerd.' where klant='ARAG' and merk='Schaatsclinics 2025';
update public.deals set won_at='2026-06-10', archived_at='2026-06-16', afsluit_notitie='Titelpartner Dam tot Damloop rond; contract getekend.' where klant='ARAG' and merk='Dam tot Damloop';
update public.deals set won_at='2026-06-16', archived_at='2026-06-21', afsluit_notitie='Regionale sc Cambuur-samenwerking getekend.' where klant='Univé Dichtbij' and merk='sc Cambuur';

-- Reden + archiveerdatum voor de onbenutte kansen
update public.deals set archived_at='2026-06-19', verwijder_reden='Club koos voor een andere partner.' where klant='Eurojackpot' and merk='Fortuna Sittard';
update public.deals set archived_at='2026-06-05', verwijder_reden='Budget dit seizoen niet rondgekomen.' where klant='Univé Zuid-Nederland' and merk='Schaatsclinics';
