-- ============================================================
--  DE COMMERCIËLE DUGOUT · Tabblad "Toekomst"
--  Draai in: Supabase → SQL Editor → New query → Run
--  Veilig om meerdere keren te draaien (IF NOT EXISTS / drop-create policies).
--
--  1. Tabel 'toekomst': kansen die eraan komen maar nog geen saleskans zijn
--     (bijv. "Univé: partnership Feyenoord opent vanaf Q4") met links en bijlagen.
--  2. Storage-bucket 'dugout-bijlagen': echte opslag voor documenten en
--     screenshots (zowel bij Toekomst-items als bij saleskansen).
--  3. RLS: alleen ingelogde gebruikers · realtime aan.
-- ============================================================

-- 1) Tabel ---------------------------------------------------
create table if not exists public.toekomst (
  id              bigint generated by default as identity primary key,
  titel           text  not null default '',
  merk            text  not null default '',
  unit            text  not null default '',
  verwacht_vanaf  text  not null default '',   -- vrij veld: "Q4 2026", "zomer 2027", ...
  omschrijving    text  not null default '',
  links           jsonb not null default '[]'::jsonb,  -- [{label,url}]
  bijlagen        jsonb not null default '[]'::jsonb,  -- [{name,path,size,type}]
  status          text  not null default 'open',       -- open / omgezet / vervallen
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists toekomst_set_updated_at on public.toekomst;
create trigger toekomst_set_updated_at
  before update on public.toekomst
  for each row execute function public.set_updated_at();

-- 2) RLS: alleen ingelogde gebruikers ------------------------
alter table public.toekomst enable row level security;
drop policy if exists "toekomst_authenticated_access" on public.toekomst;
create policy "toekomst_authenticated_access"
  on public.toekomst
  for all
  to authenticated
  using (true)
  with check (true);

-- 3) Realtime aanzetten --------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='toekomst'
  ) then
    alter publication supabase_realtime add table public.toekomst;
  end if;
end $$;
alter table public.toekomst replica identity full;

-- 4) Storage-bucket voor bijlagen (privé; alleen ingelogd) ---
insert into storage.buckets (id, name, public)
values ('dugout-bijlagen','dugout-bijlagen', false)
on conflict (id) do nothing;

drop policy if exists "dugout_bijlagen_select" on storage.objects;
create policy "dugout_bijlagen_select" on storage.objects
  for select to authenticated using (bucket_id='dugout-bijlagen');

drop policy if exists "dugout_bijlagen_insert" on storage.objects;
create policy "dugout_bijlagen_insert" on storage.objects
  for insert to authenticated with check (bucket_id='dugout-bijlagen');

drop policy if exists "dugout_bijlagen_update" on storage.objects;
create policy "dugout_bijlagen_update" on storage.objects
  for update to authenticated
  using (bucket_id='dugout-bijlagen') with check (bucket_id='dugout-bijlagen');

drop policy if exists "dugout_bijlagen_delete" on storage.objects;
create policy "dugout_bijlagen_delete" on storage.objects
  for delete to authenticated using (bucket_id='dugout-bijlagen');
